services:
    gojob:
        container_name: gojob
        env_file: .env
        image: devjunio/gojob
        ports:
            - "8080:${APP_PORT:-8080}"
        environment:
            GIN_MODE: "release"
            DB_HOST: "${DB_HOST:-database}"

    database:
        hostname: database
        image: postgres
        env_file: .env
        ports:
            - "5432:${DB_PORT:-5432}"
        environment:
            POSTGRES_PASSWORD: "db.pass"
            POSTGRES_USER: "db.user"
            POSTGRES_DB: "db.name"
        depends_on:
            - gojob
