definitions:
    model.OpeningRequest:
    properties:
      company:
          example: Google
        type: string
      link:
          example: https://google.com
        type: string
      location:
          example: Remote
        type: string
      remote:
          example: true
        type: boolean
      role:
          example: Software Engineer
        type: string
      salary:
          example: 100000
        type: integer
    type: object
    model.OpeningResponse:
    properties:
      company:
          example: Google
        type: string
      createdAt:
          example: "2021-01-01T00:00:00Z"
        type: string
      deletedAt:
          example: "2021-01-01T00:00:00Z"
        type: string
      id:
          example: 1
        type: integer
      link:
          example: https://google.com
        type: string
      location:
          example: Remote
        type: string
      remote:
          example: true
        type: boolean
      role:
          example: Software Engineer
        type: string
      salary:
          example: 100000
        type: integer
      updatedAt:
          example: "2021-01-01T00:00:00Z"
          type: string
    type: object
    router.ErrorResponse:
        properties:
            errorCode:
                example: "404"
                type: string
            message:
                example: User not found
        type: string
    type: object
info:
  contact: {}
paths:
  /openings:
    delete:
      consumes:
      - application/json
      description: Delete a job opening resource based on its unique identifier.
      parameters:
      - description: Opening identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
          description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Remove Job Opening
      tags:
      - Openings
    get:
      consumes:
      - application/json
      description: Retrieve a complete list of job openings stored in the system.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              items:
                  $ref: '#/definitions/model.OpeningResponse'
              type: array
        "500":
          description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Retrieve Job Opening List
      tags:
      - Openings
    patch:
      consumes:
      - application/json
      description: Update an existing job opening with the provided changes.
      parameters:
      - description: Opening Identification
        in: query
        name: id
        required: true
        type: string
      - description: Opening data to Update
        in: body
        name: opening
        required: true
        schema:
            $ref: '#/definitions/model.OpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
          description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Modify Job Opening
      tags:
      - Openings
    post:
      consumes:
      - application/json
      description: Add a new job opening to the system using a JSON request.
      parameters:
          -   description: Opening data to create
        in: body
              name: opening
        required: true
        schema:
            $ref: '#/definitions/model.OpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
            description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Initiate Job Opening Creation
      tags:
      - Openings
  /openings/:id:
    get:
      consumes:
      - application/json
      description: Fetch detailed information about the first job opening based on
          its unique identifier.
      parameters:
      - description: Opening identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "500":
            description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Retrieve Job Opening Details by ID
      tags:
      - Openings
swagger: "2.0"
