definitions:
    model.OpeningRequest:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
    model.OpeningResponse:
    properties:
      company:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
      updatedAt:
          type: string
    type: object
    router.ErrorResponse:
        properties:
            errorCode:
                type: string
            message:
        type: string
    type: object
info:
  contact: {}
paths:
  /openings:
    delete:
      consumes:
      - application/json
      description: Delete a new job opening
      parameters:
      - description: Opening identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
          description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Delete opening
      tags:
      - Openings
    get:
      consumes:
      - application/json
      description: List all job opening
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              items:
                  $ref: '#/definitions/model.OpeningResponse'
              type: array
        "500":
          description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: List Openings
      tags:
      - Openings
    patch:
      consumes:
      - application/json
      description: Update a job opening
      parameters:
      - description: Opening Identification
        in: query
        name: id
        required: true
        type: string
      - description: Opening data to Update
        in: body
        name: opening
        required: true
        schema:
            $ref: '#/definitions/model.OpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
          description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Update opening
      tags:
      - Openings
    post:
      consumes:
      - application/json
      description: Create a new job opening
      parameters:
          -   description: Opening data to create
        in: body
            name: opening
        required: true
        schema:
            $ref: '#/definitions/model.OpeningRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "400":
          description: Bad Request
          schema:
              $ref: '#/definitions/router.ErrorResponse'
        "404":
            description: Not Found
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Create opening
      tags:
      - Openings
  /openings/:id:
    get:
      consumes:
      - application/json
      description: Get first opening by ID
      parameters:
      - description: Opening identification
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
              $ref: '#/definitions/model.OpeningResponse'
        "500":
            description: Internal Server Error
          schema:
              $ref: '#/definitions/router.ErrorResponse'
      summary: Get Openings
      tags:
      - Openings
swagger: "2.0"
